![data-x](http://oi64.tinypic.com/o858n4.jpg)






# Homework 03


## NAME: Jeff Peng


## STUDENT ID: 3034340183



## Numpy Introduction


__1a) Create two numpy arrays (a and b). a should be all integers between 25-34 (inclusive), and b should be ten evenly spaced numbers between 1-6. Print all the results below:__ 


i) Cube (i.e. raise to the power of 3) all the elements in both arrays (element-wise)  
ii)  Add both the cubed arrays (e.g., [1,2] + [3,4] = [4,6])  
iii)  Sum the elements with even indices of the added array.  
iv)  Take the square root of the added array (element-wise square root)__


In [2]:
import numpy as np
a=np.array(range(25,35))
b=np.linspace(1,6,10)
cube_a=a**3
cube_b=b**3
addition=cube_a+cube_b
sum_even_indices=(addition[0]+addition[2]+addition[4]+addition[6]+addition[8])
sqrt=addition**0.5
print(a)
print(b)
print(cube_a)
print(cube_b)
print(addition)
print(sum_even_indices)
print(sqrt)


[25 26 27 28 29 30 31 32 33 34]
[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]
[15625 17576 19683 21952 24389 27000 29791 32768 35937 39304]
[  1.           3.76406036   9.40877915  18.96296296  33.45541838
  53.91495199  81.37037037 116.85048011 161.38408779 216.        ]
[15626.         17579.76406036 19692.40877915 21970.96296296
 24422.45541838 27053.91495199 29872.37037037 32884.85048011
 36098.38408779 39520.        ]
125711.61865569273
[125.00399994 132.58870261 140.32964327 148.22605359 156.27685503
 164.48074341 172.83625306 181.34180566 189.99574755 198.79637824]


__1b) Append b to a, reshape the appended array so that it is a 4x5, 2d array and store the results in a variable called m. Print m.__


In [3]:
m=np.append(a,b).reshape(4,5)
print(m)

[[25.         26.         27.         28.         29.        ]
 [30.         31.         32.         33.         34.        ]
 [ 1.          1.55555556  2.11111111  2.66666667  3.22222222]
 [ 3.77777778  4.33333333  4.88888889  5.44444444  6.        ]]


__1c) Extract the third and the fourth column of the m matrix. Store the resulting 4x2 matrix in a new variable called m2. Print m2.__


In [4]:
m2=m[:,2:4]
print(m2)


[[27.         28.        ]
 [32.         33.        ]
 [ 2.11111111  2.66666667]
 [ 4.88888889  5.44444444]]


__1d) Take the dot product of m2 and m store the results in a matrix called m3. Print m3.
Note that Dot product of two matrices A.B =A<sup>T</sup>B__

In [5]:
c = np.transpose(m2)
m3=np.matmul(c,m)
print(m3)

[[1655.58024691 1718.4691358  1781.35802469 1844.24691358 1907.13580247]
 [1713.2345679  1778.74074074 1844.24691358 1909.75308642 1975.25925926]]


__1e) Round the m3 matrix to three decimal points. Store the result in place and print the new m3.__


In [6]:
rounded=np.around(m3,decimals=3)
m3=rounded
print(m3)

[[1655.58  1718.469 1781.358 1844.247 1907.136]
 [1713.235 1778.741 1844.247 1909.753 1975.259]]


__1f) Sort the m3 array so that the highest value is at the bottom right and the lowest value is at the top left. Print the sorted m3 array.__


In [7]:
sort_m3_flat=np.sort(m3,axis=None)
sort_m3=sort_m3_flat.reshape(2,5)
print(sort_m3)


[[1655.58  1713.235 1718.469 1778.741 1781.358]
 [1844.247 1844.247 1907.136 1909.753 1975.259]]


## NumPy and Masks
__2a) create an array called 'f' where the values are cosine(x) for x from 0 to pi with 50 equally spaced values in f__
* print f
* use a 'mask' and print an array that is True when f >= 1/2 and False when f < 1/2
* create and print an array sequence that has only those values where f>= 1/2



In [13]:
from math import *
f=np.cos(np.linspace(0,pi,50))
print(f)
mask=f>=0.5
print(mask)
print(f[mask])


[ 1.          0.99794539  0.99179001  0.98155916  0.96729486  0.94905575
  0.92691676  0.90096887  0.8713187   0.8380881   0.80141362  0.76144596
  0.71834935  0.67230089  0.6234898   0.57211666  0.51839257  0.46253829
  0.40478334  0.34536505  0.28452759  0.22252093  0.1595999   0.09602303
  0.03205158 -0.03205158 -0.09602303 -0.1595999  -0.22252093 -0.28452759
 -0.34536505 -0.40478334 -0.46253829 -0.51839257 -0.57211666 -0.6234898
 -0.67230089 -0.71834935 -0.76144596 -0.80141362 -0.8380881  -0.8713187
 -0.90096887 -0.92691676 -0.94905575 -0.96729486 -0.98155916 -0.99179001
 -0.99794539 -1.        ]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]
[1.         0.99794539 0.99179001 0.98155916 0.96729486 0.94905575
 0.92691676 0.90096

## NumPy and 2 Variable Prediction

__ Let 'x' be the number of miles a person drives per day and 'y' be the dollars spent on buying car fuel (per day).__
  
__We have created 2 numpy arrays each of size 100 that represent x and y.  
x ( number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
y (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1)__ 


In [14]:
# seed the random number generator with a fixed value
import numpy as np
np.random.seed(500)

x=np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y=np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print ('x = ',x)
print ('y= ',y)

x =  [ 1.34683976  1.12176759  1.51512398  1.55233174  1.40619168  1.65075498
  1.79399331  1.80243817  1.89844195  2.00100023  2.3344038   2.22424872
  2.24914511  2.36268477  2.49808849  2.8212704   2.68452475  2.68229427
  3.09511169  2.95703884  3.09047742  3.2544361   3.41541904  3.40886375
  3.50672677  3.74960644  3.64861355  3.7721462   3.56368566  4.01092701
  4.15630694  4.06088549  4.02517179  4.25169402  4.15897504  4.26835333
  4.32520644  4.48563164  4.78490721  4.84614839  4.96698768  5.18754259
  5.29582013  5.32097781  5.0674106   5.47601124  5.46852704  5.64537452
  5.49642807  5.89755027  5.68548923  5.76276141  5.94613234  6.18135713
  5.96522091  6.0275473   6.54290191  6.4991329   6.74003765  6.81809807
  6.50611821  6.91538752  7.01250925  6.89905417  7.31314433  7.20472297
  7.1043621   7.48199528  7.58957227  7.61744354  7.6991707   7.85436822
  8.03510784  7.80787781  8.22410224  7.99366248  8.40581097  8.28913792
  8.45971515  8.54227144  8.6906456   8.618565

__3a) Find Expected value of x and the expected value of y__

In [15]:
E_x=np.mean(x)
E_y=np.mean(y)
print(E_x)
print(E_y)

5.782532541587923
11.012981683344968


__3b) Find variance of distributions of  x and  y__

In [16]:
Var_x=np.var(x)
Var_y=np.var(y)
print(Var_x)
print(Var_y)


7.03332752947585
30.113903575509635


__3c) Find co-variance of x and y.__

In [17]:
E_xy=np.mean(x*y)
cov=E_xy-E_x*E_y
print(cov)

14.511166394475424


__3d) Assuming that number of dollars spent in car fuel is only dependant on the miles driven, by  a linear relationship.  
Write code that uses a linear predictor to calculate a predicted value of y for each x
ie y_predicted = f(x) = y0+mx.__  

In [18]:
y_0=E_y-cov/Var_x*E_x
slope=cov/Var_x
y_pred=slope*x+y_0
print(y_pred)

[ 1.86125717  1.39688809  2.20846128  2.28522836  1.98371207  2.48829527
  2.78382468  2.80124813  2.9993232   3.21092152  3.8988      3.67152796
  3.7228942   3.9571493   4.23651436  4.9033035   4.62116978  4.61656787
  5.46829307  5.18342105  5.45873164  5.79701128  6.12915141  6.11562653
  6.31753758  6.81864709  6.61027849  6.86515115  6.43505522  7.35780389
  7.65775187  7.46087825  7.38719373  7.85455455  7.66325667  7.88892606
  8.00622544  8.33721481  8.95468038  9.08103323  9.33034895  9.78539799
 10.00879629 10.06070164  9.53754157 10.38056671 10.36512531 10.72999716
 10.42269073 11.25028634 10.81276185 10.97218988 11.35052091 11.83583685
 11.38990445 11.51849632 12.58177632 12.49147206 12.98850691 13.14956122
 12.50588416 13.35028889 13.5506705  13.31658991 14.17094102 13.947246
 13.74018137 14.51931443 14.74126735 14.79877137 14.96739089 15.28759454
 15.66049665 15.1916755  16.05043004 15.57498655 16.42533161 16.18461169
 16.53654675 16.70687695 17.01300263 16.86428603 17.3

__3e) Predict y for each value in x, pur the error into an array called y_error__

In [21]:
y_error=(y_pred-y)
print(y_error)

[ 0.19775597 -0.62457111  0.10030076  0.02506341  0.02083649 -0.46716823
 -0.24499418 -0.53440482  0.24466541 -0.21408918  0.50209852  0.27775029
 -0.06213923 -0.42578118 -0.0931215   0.86405311 -0.1157489   0.31558388
  0.62666017  0.40166149  0.46107377  0.47954311  0.3607047   0.17838904
  0.58942116  0.10891094 -0.07115518  0.29032384 -0.74232081 -0.19082863
  0.35553767  0.14062095 -0.39304511 -0.0567791  -0.61328502 -0.80310676
 -0.77597321 -0.12176065  0.06373323  0.26383402  0.45927925  0.12347238
  0.60673379  0.20079382 -0.0660562   0.30670405 -0.33067419  0.062778
 -0.75987212  0.67596798 -0.65468531  0.02820071  0.08606832 -0.26171143
 -0.72997592 -0.60306068  0.40563939  0.05397013 -0.02061681  0.28548928
 -0.7405245   0.58908804  0.43343988 -0.76182107 -0.02727604 -0.32564401
 -0.56606805 -0.11129392  0.46417555 -0.27572093  0.5147747   0.16862142
  0.42262995 -0.08035574  0.72551112 -0.43596616  0.71282602 -0.11027337
 -0.16964259  0.14132301  0.58920807 -0.31716141  0.1

__3f) Write code that calculates the root mean square error(RMSE), that is root of average of y-error squared__

In [20]:
squared_error=np.mean(np.square(y_pred-y))
rmse=squared_error**0.5
print(rmse)

0.41767772366856115
